# Generated by Django 4.1.7 on 2023-03-21 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesses', models.CharField(max_length=50)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('qtd_atendimento', models.IntegerField(blank=True, max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='DadosPessoais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14)),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=30)),
                ('telefone', models.CharField(max_length=12)),
                ('senha', models.CharField(max_length=30)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_dados_pessoais')),
            ],
        ),
        migrations.CreateModel(
            name='Estabelecimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('endereco', models.CharField(max_length=50)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_estabelecimentos')),
                ('localizacao', models.ImageField(blank=True, null=True, upload_to='imagens_locais')),
            ],
        ),
        migrations.CreateModel(
            name='Funcoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especificacao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Gerente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.DecimalField(decimal_places=2, max_digits=7)),
                ('dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Razor.dadospessoais')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Razor.estabelecimento')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('quantidade', models.IntegerField(max_length=5)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Profissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biografia', models.CharField(max_length=30)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('gastos', models.DecimalField(decimal_places=2, max_digits=6)),
                ('dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Razor.dadospessoais')),
                ('estabelecimento_trabalho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Razor.estabelecimento')),
                ('funcoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Razor.funcoes')),
                ('gerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Razor.gerente')),
            ],
        ),
        migrations.CreateModel(
            name='VendasCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Razor.cliente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Razor.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='VendaProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Razor.produtos')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Razor.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutosTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Razor.produtos')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Razor.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='FuncoesProfissional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcoes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Razor.funcoes')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Razor.profissional')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='dados_pessoais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Razor.dadospessoais'),
        ),
        migrations.CreateModel(
            name='Atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Razor.cliente')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Razor.profissional')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dados_pessoais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Razor.dadospessoais')),
                ('estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='The_Razor.estabelecimento')),
            ],
        ),
    ]
