# Generated by Django 4.1.7 on 2023-03-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Razor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='qtd_atendimento',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='quantidade',
            field=models.IntegerField(),
        ),
    ]
