# Generated by Django 4.1.7 on 2023-03-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('The_Razor', '0002_alter_cliente_qtd_atendimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtostrabalho',
            name='quantidade_cedida',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendaprofissional',
            name='quantidade_vendida',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vendascliente',
            name='quantidade_vendida',
            field=models.IntegerField(default=0),
        ),
    ]
